name: 'retail_dbt'
version: '1.0.0'
config-version: 2

profile: 'retail_dbt'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  retail_dbt:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: ANALYTICS
      +materialized: table
