version: 2

models:
  - name: fact_sales
    columns:
      - name: sales_line_key
        tests:
          - not_null
          - unique

      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key

      - name: store_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_store')
              field: store_key

      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key

      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key

  - name: fact_inventory_snapshot
    columns:
      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key

      - name: store_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_store')
              field: store_key

      - name: product_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_product')
              field: product_key
